workshop_schema_version = 1

[github]
auto_sync = false

[layout]
sidebar_width = 452.26563
sparks_width = 350.04688
sidebar_split = 0.4497009

[explorer]
ignore = [
    ".git",
    ".ryve",
    "node_modules",
    "target",
    ".DS_Store",
    "__pycache__",
    ".venv",
    "venv",
    ".mypy_cache",
    ".pytest_cache",
    ".ruff_cache",
    "dist",
    "build",
    ".next",
    ".turbo",
]

[background]
image = "pawel-czerwinski-LSZE-N0hz3s-unsplash.jpg"
dim_opacity = 0.7

[agents]
disable_sync = false
